site_name: My Docs
site_name: DeLeakage

extra:
  no_mkdocs_2_warning: true

theme:
  name: material
  custom_dir: overrides
  language: en
  palette:
    primary: indigo
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs  # 顶部导航标签
    - navigation.sections  # 侧边栏分组
    - toc.integrate  # 目录整合到侧边栏
    - header.autohide  # 滚动时自动隐藏顶部栏
    - content.code.copy

# 右上角 GitHub 仓库链接
repo_url: https://github.com/JasonLiDataSci/deContamination
repo_name: deContamination

# 顶部导航栏
nav:
  - Home: index.md
  - Install: install.md
  - Quick Start: quickstart.md
  - GPU Implementation: gpu_tutorial.md

# Markdown 扩展
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - attr_list
  - md_in_html

